package com.prafullkumar.recipeharbour.presentations.homeScreen

object HomeConstants {
    private val indianDishes = listOf(
        "Biryani",
        "Butter Chicken",
        "Masala Dosa",
        "Chole Bhature",
        "Paneer Tikka",
        "Rogan Josh",
        "Vada Pav",
        "Palak Paneer",
        "Pani Puri/Golgappa",
        "Hyderabadi Dum Biryani",
        "Samosa",
        "Tandoori Chicken",
        "Aloo Paratha",
        "Chicken Tikka Masala",
        "Dal Makhani",
        "Rajma Chawal",
        "Mutton Curry",
        "Fish Curry",
        "Dhokla",
        "Pav Bhaji",
        "Idli-Sambhar",
        "Jalebi",
        "Keema",
        "Malai Kofta",
        "Kheer",
        "Matar Paneer",
        "Chicken Korma",
        "Gajar Ka Halwa",
        "Aloo Gobi",
        "Shahi Paneer",
        "Bhel Puri",
        "Chicken Curry",
        "Chicken 65",
        "Rasgulla",
        "Moong Dal Halwa",
        "Chicken Biryani",
        "Tandoori Fish",
        "Litti Chokha",
        "Kashmiri Pulao",
        "Bhindi Masala",
        "Aloo Matar",
        "Gobi Manchurian",
        "Chicken Do Pyaza",
        "Kachori",
        "Patra",
        "Chana Masala",
        "Mysore Pak",
        "Bhutte Ka Kees",
        "Sheer Khurma",
        "Undhiyu"
    )
    private val chineseCuisines = listOf(
        "Peking Duck",
        "Kung Pao Chicken",
        "Dim Sum",
        "Mapo Tofu",
        "Hot Pot",
        "Chow Mein",
        "Spring Rolls",
        "Sweet and Sour Pork",
        "Baozi (Steamed Buns)",
        "Sichuan Hotpot",
        "Wontons",
        "Shanghai Noodles",
        "Ma La Xiang Guo (Spicy Hot Pot)",
        "Gong Bao Ji Ding (Gong Bao Chicken)",
        "Char Siu (Barbecue Pork)",
        "Lo Mein",
        "General Tso's Chicken",
        "Xiaolongbao (Soup Dumplings)",
        "Zhajiangmian (Fried Sauce Noodles)",
        "Cantonese Roast Duck",
        "Hainanese Chicken Rice",
        "Jiaozi (Chinese Dumplings)",
        "Dan Dan Noodles",
        "Beef and Broccoli",
        "Scallion Pancakes",
        "Dongpo Pork",
        "Three-Cup Chicken",
        "Har Gow (Shrimp Dumplings)",
        "Beijing Fried Sauce Noodles (Zhajiangmian)",
        "Fish-Flavored Shredded Pork",
        "Tangyuan (Glutinous Rice Balls)",
        "Congee",
        "Moo Shu Pork",
        "Salt and Pepper Shrimp",
        "Chow Fun (Stir-Fried Rice Noodles)",
        "Szechuan Beef",
        "Clay Pot Rice",
        "Lion's Head Meatballs",
        "Twice-Cooked Pork",
        "Tea-Smoked Duck",
        "Eight Treasure Duck",
        "Beggar's Chicken",
        "Buddha's Delight (Vegetarian Stir-Fry)",
        "Crispy Tofu",
        "Chongqing Chicken",
        "Shrimp with Lobster Sauce",
        "Zongzi (Sticky Rice Dumplings)",
        "Ants Climbing a Tree (Ma Yi Shang Shu)",
        "Snow Peas and Water Chestnuts Stir-Fry",
        "Dan Dan Mian"
    )
    private val europeanCuisines = listOf(
        "Pizza",
        "Pasta Carbonara",
        "Croissant",
        "Paella",
        "Fish and Chips",
        "Wiener Schnitzel",
        "Ratatouille",
        "Moules Marinière (Mussels)",
        "Goulash",
        "Bangers and Mash",
        "Coq au Vin",
        "Shepherd's Pie",
        "Spanakopita",
        "Beef Bourguignon",
        "Tiramisu",
        "Bouillabaisse",
        "Risotto",
        "Pâté en Croûte",
        "Haggis",
        "Sauerbraten",
        "Stroganoff",
        "Chicken Kiev",
        "Knödel (Dumplings)",
        "Baklava",
        "Ceviche",
        "Escargot",
        "Beef Wellington",
        "Pierogi",
        "Jansson's Temptation",
        "Königsberger Klopse (Meatballs in White Sauce)",
        "Pirozhki",
        "Quiche Lorraine",
        "Cullen Skink",
        "Moussaka",
        "Lapland's Sautéed Reindeer",
        "Trinxat",
        "Matjes Herring",
        "Ossobuco",
        "Scouse",
        "Tarte Tatin",
        "Black Forest Cake",
        "Carpaccio",
        "Beef Olives",
        "Yorkshire Pudding",
        "Lobster Thermidor",
        "Panzanella",
        "Smørrebrød",
        "Welsh Rarebit",
        "Kaiserschmarrn",
        "Pheasant à la Normande"
    )
    fun getRandom10IndianDishes(): List<String> {
        return indianDishes.shuffled().take(10)
    }
    fun getRandom10ChineseDishes(): List<String> {
        return chineseCuisines.shuffled().take(10)
    }
    fun getRandom10EuropeanDishes(): List<String> {
        return europeanCuisines.shuffled().take(10)
    }
}